// BungieReactApp3/src/pages/Admin2.jsx
import React, { useEffect, useState } from 'react';
import { Container, Row, Col, Card, Table, Spinner, Alert } from 'react-bootstrap';
import { Link } from 'react-router-dom';

const SUMMARY_API = 'https://localhost:7226/api/SuperHeroUniverse/admin-summary';

export default function Admin2() {
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    const fetchSummary = async () => {
      setLoading(true);
      setError('');
      try {
        const res = await fetch(SUMMARY_API);
        if (!res.ok) throw new Error('Failed to fetch summary');
        const data = await res.json();
        setSummary(data);
      } catch (err) {
        setError('Error loading admin summary');
      } finally {
        setLoading(false);
      }
    };
    fetchSummary();
  }, []);

  return (
    <Container className="mt-4">
      <Row className="justify-content-center">
        <Col md={8}>
          <Card className="shadow-sm mb-4">
            <Card.Body>
              <Card.Title as="h2" className="mb-3">Admin2 Page</Card.Title>
              <Card.Text>
                This is a placeholder for the Admin2 page. Add your admin features and controls here.
              </Card.Text>
              <Card.Text>
                <div className="d-flex flex-wrap gap-2">
                  <Link to="/super-heroes" className="btn btn-primary">
                    Go to Super Heroes
                  </Link>
                  <Link to="/super-powers" className="btn btn-secondary">
                    Go to Super Powers
                  </Link>
                  <Link to="/sidekick" className="btn btn-info">
                    Go to SideKick
                  </Link>
                  <Link to="/comic-appearance" className="btn btn-warning">
                    Go to Comic Appearance
                  </Link>
                  <Link to="/sidekick-comic-appearance" className="btn btn-success">
                    Go to SideKick Comic Appearance
                  </Link>
                  <Link to="/product-stock" className="btn btn-success">
                    Go to Product Stock
                  </Link>
                  <Link to="/all-orders" className="btn btn-dark">
                    Go To All Orders
                  </Link>
                  <Link to="/user-extra-info" className="btn btn-outline-info">
                    Go to User Extra Info
                  </Link>
                  <Link to="/advanced-user-management" className="btn btn-outline-info">
                    Go to Advanced User Management
                  </Link>
                </div>
              </Card.Text>
            </Card.Body>
          </Card>
          <Card className="shadow-sm">
            <Card.Body>
              <Card.Title as="h4" className="mb-3">Admin Summary</Card.Title>
              {loading ? (
                <div className="text-center"><Spinner animation="border" /></div>
              ) : error ? (
                <Alert variant="danger">{error}</Alert>
              ) : summary ? (
                <Table bordered>
                  <tbody>
                    <tr>
                      <th>Super Hero Count</th>
                      <td>{summary.superHeroCount}</td>
                    </tr>
                    <tr>
                      <th>Super Power Count</th>
                      <td>{summary.superPowerCount}</td>
                    </tr>
                    <tr>
                      <th>Sidekick Count</th>
                      <td>{summary.sidekickCount}</td>
                    </tr>
                    <tr>
                      <th>Comic Appearance Count</th>
                      <td>{summary.comicAppearanceCount}</td>
                    </tr>
                    <tr>
                      <th>Sidekick Comic Appearance Count</th>
                      <td>{summary.sidekickComicAppearanceCount}</td>
                    </tr>
                    <tr>
                      <th>User Count</th>
                      <td>{summary.userCount}</td>
                    </tr>
                    <tr>
                      <th>Role Count</th>
                      <td>{summary.roleCount}</td>
                    </tr>
                  </tbody>
                </Table>
              ) : null}
            </Card.Body>
          </Card>
        </Col>
      </Row>
    </Container>
  );
}

// BungieCordBlogAngular2/src/app/features/admin2/admin2.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';

interface AdminSummary {
  superHeroCount: number;
  superPowerCount: number;
  sidekickCount: number;
  comicAppearanceCount: number;
  sidekickComicAppearanceCount: number;
  userCount: number;
  roleCount: number;
}

@Component({
  selector: 'app-admin2',
  templateUrl: './admin2.component.html'
})
export class Admin2Component implements OnInit {
  summary: AdminSummary | null = null;
  loading = false;
  error = '';

  constructor(private http: HttpClient) {}

  ngOnInit() {
    this.loading = true;
    this.http.get<AdminSummary>('https://localhost:7226/api/SuperHeroUniverse/admin-summary')
      .subscribe({
        next: data => {
          this.summary = data;
          this.loading = false;
        },
        error: () => {
          this.error = 'Could not load admin summary.';
          this.loading = false;
        }
      });
  }
}
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-md-8 text-center">
      <h2>Admin2 Section</h2>
      <p>This is a placeholder for the Admin2 component. Content coming soon!</p>
      <a class="btn btn-primary mt-3" routerLink="/superhero">Go to SuperHero</a>
      <a class="btn btn-secondary mt-3 ms-2" routerLink="/superpower">Go to SuperPower</a>
      <a class="btn btn-info mt-3 ms-2" routerLink="/sidekick">Go to Sidekick</a>
      <a class="btn btn-warning mt-3 ms-2" routerLink="/comicappearance">Go to ComicAppearance</a>
      <a class="btn btn-dark mt-3 ms-2" routerLink="/sidekickcomicappearance">Go to SidekickComicAppearance</a>
    </div>
  </div>
  <div class="row justify-content-center mt-5">
    <div class="col-md-8">
      <div *ngIf="loading" class="text-center my-3">
        <span class="spinner-border"></span> Loading summary...
      </div>
      <div *ngIf="error" class="alert alert-danger text-center">{{ error }}</div>
      <div *ngIf="summary && !loading">
        <h4 class="text-center mb-4">Admin Summary</h4>
        <table class="table table-bordered table-striped">
          <tbody>
            <tr>
              <th>SuperHero Count</th>
              <td>{{ summary.superHeroCount }}</td>
            </tr>
            <tr>
              <th>SuperPower Count</th>
              <td>{{ summary.superPowerCount }}</td>
            </tr>
            <tr>
              <th>Sidekick Count</th>
              <td>{{ summary.sidekickCount }}</td>
            </tr>
            <tr>
              <th>Comic Appearance Count</th>
              <td>{{ summary.comicAppearanceCount }}</td>
            </tr>
            <tr>
              <th>Sidekick Comic Appearance Count</th>
              <td>{{ summary.sidekickComicAppearanceCount }}</td>
            </tr>
            <tr>
              <th>User Count</th>
              <td>{{ summary.userCount }}</td>
            </tr>
            <tr>
              <th>Role Count</th>
              <td>{{ summary.roleCount }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
