// BungieReactApp3/src/pages/SuperHeroDetails.jsx
import React, { useState, useEffect } from 'react';
import { Card, Table, Button, Row, Col, Alert, Modal, Spinner } from 'react-bootstrap';

const PRODUCT_STOCK_API = 'https://localhost:7226/api/ProductStock/by-superhero';

export default function SuperHeroDetails({
  detailsHero,
  detailsLoading,
  detailsError,
  detailsPowers,
  detailsSidekicks,
  detailsComics,
  detailsImages,
  onClose
}) {
  const [selectedImage, setSelectedImage] = useState(null);
  const [productStock, setProductStock] = useState(null);
  const [stockLoading, setStockLoading] = useState(false);
  const [stockError, setStockError] = useState('');

useEffect(() => {
  // Debug: log detailsHero
  console.log('SuperHeroDetails detailsHero:', detailsHero);

  if (!detailsHero || !detailsHero.id) return;
  const fetchProductStock = async () => {
    setStockLoading(true);
    setStockError('');
    try {
      const res = await fetch(`${PRODUCT_STOCK_API}/${detailsHero.id}`);
      if (!res.ok) throw new Error('Failed to fetch product stock');
      const data = await res.json();
      setProductStock(data);
    } catch (err) {
      setStockError('Error loading product stock');
    } finally {
      setStockLoading(false);
    }
  };
  fetchProductStock();
}, [detailsHero?.id]);

  const handleImageClick = (img) => {
    setSelectedImage(img);
  };

  const handleCloseImageModal = () => {
    setSelectedImage(null);
  };

  return (
    <Card className="mt-4 shadow-sm">
      <Card.Body>
        <Card.Title as="h4">Super Hero Details - Admin View</Card.Title>
        {detailsLoading ? (
          <div className="text-center"><span className="spinner-border" /></div>
        ) : detailsError ? (
          <Alert variant="danger">{detailsError}</Alert>
        ) : detailsHero ? (
          <>
            <Table bordered>
              <tbody>
                <tr>
                  <th>Name</th>
                  <td>{detailsHero.name}</td>
                </tr>
                <tr>
                  <th>Alias</th>
                  <td>{detailsHero.alias}</td>
                </tr>
                <tr>
                  <th>Age</th>
                  <td>{detailsHero.age}</td>
                </tr>
                <tr>
                  <th>Origin</th>
                  <td>{detailsHero.origin}</td>
                </tr>
                <tr>
                  <th>First Appearance</th>
                  <td>{detailsHero.firstAppearance?.replace('T', ' ').slice(0, 16)}</td>
                </tr>
                <tr>
                  <th>Active</th>
                  <td>{detailsHero.isActive ? 'Yes' : 'No'}</td>
                </tr>
              </tbody>
            </Table>
            <h5 className="mt-4">Super Powers</h5>
            {detailsPowers.length === 0 ? (
              <div>No powers found.</div>
            ) : (
              <Table bordered>
                <thead>
                  <tr>
                    <th>Power Name</th>
                    <th>Description</th>
                  </tr>
                </thead>
                <tbody>
                  {detailsPowers.map((power) => (
                    <tr key={power.id}>
                      <td>{power.powerName}</td>
                      <td>{power.description}</td>
                    </tr>
                  ))}
                </tbody>
              </Table>
            )}
            <h5 className="mt-4">Sidekicks</h5>
            {detailsSidekicks.length === 0 ? (
              <div>No sidekicks found.</div>
            ) : (
              <Table bordered>
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Age</th>
                  </tr>
                </thead>
                <tbody>
                  {detailsSidekicks.map((sk) => (
                    <tr key={sk.id}>
                      <td>{sk.name}</td>
                      <td>{sk.age}</td>
                    </tr>
                  ))}
                </tbody>
              </Table>
            )}
            <h5 className="mt-4">Comic Appearances</h5>
            {detailsComics.length === 0 ? (
              <div>No comic appearances found.</div>
            ) : (
              <Table bordered>
                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Issue</th>
                    <th>Release Date</th>
                  </tr>
                </thead>
                <tbody>
                  {detailsComics.map((comic) => (
                    <tr key={comic.id}>
                      <td>{comic.comicTitle}</td>
                      <td>{comic.issueNumber}</td>
                      <td>{comic.releaseDate?.replace('T', ' ').slice(0, 16)}</td>
                    </tr>
                  ))}
                </tbody>
              </Table>
            )}
            <h5 className="mt-4">Images</h5>
            {detailsImages.length === 0 ? (
              <div>No images found.</div>
            ) : (
              <Row className="g-3">
                {detailsImages.map((img) => (
                  <Col key={img.id} xs={12} sm={6} md={4} lg={3}>
                    <Card
                      className="h-100"
                      style={{ cursor: 'pointer' }}
                      onClick={() => handleImageClick(img)}
                    >
                      <Card.Img
                        variant="top"
                        src={img.url.startsWith('http') ? img.url : `${window.location.origin}${img.url}`}
                        alt={img.title}
                        style={{ objectFit: 'cover', height: '200px' }}
                      />
                      <Card.Body>
                        <Card.Title>{img.title}</Card.Title>
                        <Card.Text>
                          <small>
                            Uploaded: {img.dateCreated?.replace('T', ' ').slice(0, 16)}
                          </small>
                        </Card.Text>
                      </Card.Body>
                    </Card>
                  </Col>
                ))}
              </Row>
            )}
            {/* Product Stock Section */}
            <h5 className="mt-4">Product Stock</h5>
            {stockLoading ? (
              <div className="text-center"><Spinner animation="border" size="sm" /></div>
            ) : stockError ? (
              <Alert variant="danger">{stockError}</Alert>
            ) : productStock ? (
              <Table bordered>
                <tbody>
                  <tr>
                    <th>SKU</th>
                    <td>{productStock.sku}</td>
                  </tr>
                  <tr>
                    <th>Description</th>
                    <td>{productStock.description}</td>
                  </tr>
                  <tr>
                    <th>Unit Price</th>
                    <td>{productStock.unitPrice}</td>
                  </tr>
                  <tr>
                    <th>Quantity</th>
                    <td>{productStock.quantity}</td>
                  </tr>
                  <tr>
                    <th>Currency</th>
                    <td>{productStock.currency}</td>
                  </tr>
                  <tr>
                    <th>Active</th>
                    <td>{productStock.isActive ? 'Yes' : 'No'}</td>
                  </tr>
                  <tr>
                    <th>Last Updated</th>
                    <td>{productStock.lastUpdated?.replace('T', ' ').slice(0, 19)}</td>
                  </tr>
                </tbody>
              </Table>
            ) : (
              <div>No product stock found.</div>
            )}
            {/* Image Modal */}
            <Modal show={!!selectedImage} onHide={handleCloseImageModal} centered size="lg">
              <Modal.Header closeButton>
                <Modal.Title>{selectedImage?.title}</Modal.Title>
              </Modal.Header>
              <Modal.Body className="text-center">
                {selectedImage && (
                  <img
                    src={selectedImage.url.startsWith('http') ? selectedImage.url : `${window.location.origin}${selectedImage.url}`}
                    alt={selectedImage.title}
                    style={{ maxWidth: '100%', maxHeight: '70vh', borderRadius: '8px' }}
                  />
                )}
                <div className="mt-2">
                  <small>
                    Uploaded: {selectedImage?.dateCreated?.replace('T', ' ').slice(0, 16)}
                  </small>
                </div>
              </Modal.Body>
              <Modal.Footer>
                <Button variant="secondary" onClick={handleCloseImageModal}>
                  Close
                </Button>
              </Modal.Footer>
            </Modal>
          </>
        ) : null}
        <Button
          variant="secondary"
          className="mt-3"
          onClick={onClose}
        >
          Close Details
        </Button>
      </Card.Body>
    </Card>
  );
}

// BungieCordBlogAngular2/src/app/shared/components/super-hero-details/super-hero-details.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { SuperPowerService } from '../../services/superpower.service';
import { SidekickService } from '../../services/sidekick.service';
import { SuperHeroImagesService } from '../../services/superheroimages.service';
import { Sidekick } from '../../models/Sidekick.model';
import { SuperPower } from '../../models/SuperPower.model';
import { SuperHeroImage } from '../../models/SuperHeroImage.model';

interface SuperHero {
  id: string;
  name: string;
  alias: string;
  age: number;
  origin: string;
  firstAppearance: string;
  isActive: boolean;
}

interface ProductStock {
  id: string;
  superHeroId: string;
  unitPrice: number;
  quantity: number;
  sku: string;
  description: string;
  currency: string;
  isActive: boolean;
  lastUpdated: string;
}

@Component({
  selector: 'app-super-hero-details',
  templateUrl: './super-hero-details.component.html'
})
export class SuperHeroDetailsComponent implements OnInit {
  @Input() superHeroId: string = '';
  hero: SuperHero | null = null;
  loading = false;
  error = '';
  powers: SuperPower[] = [];
  sidekicks: Sidekick[] = [];
  images: SuperHeroImage[] = [];
  imageIndex = 0;
  productStock: ProductStock | null = null;

  constructor(
    private http: HttpClient,
    private route: ActivatedRoute,
    private powerService: SuperPowerService,
    private sidekickService: SidekickService,
    private imagesService: SuperHeroImagesService
  ) {}

  ngOnInit() {
    let id = this.superHeroId;
    this.route.params.subscribe(params => {
      if (params['id']) {
        id = params['id'];
      }
      if (id) {
        this.loading = true;
        this.error = '';
        this.http.get<SuperHero>(`https://localhost:7226/api/SuperHeroes/${id}`)
          .subscribe({
            next: data => {
              this.hero = data;
              this.loading = false;
              this.powerService.getBySuperHero(id).subscribe(powers => {
                this.powers = powers;
              });
              this.sidekickService.getBySuperHero(id).subscribe(sidekicks => {
                this.sidekicks = sidekicks;
              });
              this.imagesService.getImagesBySuperHero(id).subscribe(images => {
                this.images = images;
                this.imageIndex = 0;
              });
              // Fetch product stock details
              this.http.get<ProductStock>(`https://localhost:7226/api/ProductStock/by-superhero/${id}`)
                .subscribe({
                  next: stock => {
                    this.productStock = stock;
                  }
                });
            },
            error: () => {
              this.error = 'Could not load superhero details.';
              this.loading = false;
            }
          });
      }
    });
  }

  nextImage() {
    if (this.images.length > 0) {
      this.imageIndex = (this.imageIndex + 1) % this.images.length;
    }
  }

  prevImage() {
    if (this.images.length > 0) {
      this.imageIndex = (this.imageIndex - 1 + this.images.length) % this.images.length;
    }
  }
}
<div class="container my-4">
  <div *ngIf="loading" class="text-center my-3">
    <span class="spinner-border"></span> Loading...
  </div>
  <div *ngIf="error" class="alert alert-danger text-center">{{ error }}</div>
  <div *ngIf="hero && !loading">
    <div class="card mx-auto" style="max-width: 500px;">
      <div class="card-body">
        <h4 class="card-title text-center">{{ hero.name }}</h4>
        <h6 class="card-subtitle mb-2 text-muted text-center">{{ hero.alias }}</h6>
        <ul class="list-unstyled text-center mb-4">
          <li><strong>Origin:</strong> {{ hero.origin }}</li>
          <li><strong>First Appearance:</strong> {{ hero.firstAppearance | date:'yyyy-MM-dd' }}</li>
          <li><strong>Active:</strong> {{ hero.isActive ? 'Yes' : 'No' }}</li>
          <li><strong>Age:</strong> {{ hero.age }}</li>
        </ul>
        <div class="mb-4">
          <h5 class="text-center mb-2">Image Gallery</h5>
          <div *ngIf="images.length > 0" class="d-flex align-items-center justify-content-center" style="gap:8px;">
            <button class="btn btn-outline-secondary btn-sm"
                    style="height:40px; width:40px;"
                    (click)="prevImage()">
              &lt;
            </button>
            <img [src]="images[imageIndex].url"
                 [alt]="images[imageIndex].title"
                 class="img-thumbnail"
                 style="height:200px; width:180px; object-fit:cover;">
            <button class="btn btn-outline-secondary btn-sm"
                    style="height:40px; width:40px;"
                    (click)="nextImage()">
              &gt;
            </button>
          </div>
          <div *ngIf="images.length > 0" class="text-center mt-2" style="font-size:1em;">
            {{ images[imageIndex].title }}
          </div>
          <div *ngIf="images.length === 0" class="text-center text-muted">
            No images found.
          </div>
        </div>
        <h5 class="text-center mt-4 mb-2">Super Powers</h5>
        <ul class="list-group mb-4">
          <li *ngFor="let power of powers" class="list-group-item text-center">
            <strong>{{ power.powerName }}</strong>: {{ power.description }}
          </li>
          <li *ngIf="powers.length === 0" class="list-group-item text-muted text-center">No powers found.</li>
        </ul>
        <h5 class="text-center mt-4 mb-2">Sidekicks</h5>
        <ul class="list-group mb-4">
          <li *ngFor="let sidekick of sidekicks" class="list-group-item text-center">
            <strong>{{ sidekick.name }}</strong> (Age: {{ sidekick.age }})
          </li>
          <li *ngIf="sidekicks.length === 0" class="list-group-item text-muted text-center">No sidekicks found.</li>
        </ul>
        <h5 class="text-center mt-4 mb-2">Product Stock</h5>
        <div *ngIf="productStock" class="mb-3">
          <ul class="list-group">
            <li class="list-group-item"><strong>SKU:</strong> {{ productStock.sku }}</li>
            <li class="list-group-item"><strong>Description:</strong> {{ productStock.description }}</li>
            <li class="list-group-item"><strong>Unit Price:</strong> {{ productStock.unitPrice | currency:productStock.currency }}</li>
            <li class="list-group-item"><strong>Quantity:</strong> {{ productStock.quantity }}</li>
            <li class="list-group-item"><strong>Currency:</strong> {{ productStock.currency }}</li>
            <li class="list-group-item"><strong>Active:</strong> {{ productStock.isActive ? 'Yes' : 'No' }}</li>
            <li class="list-group-item"><strong>Last Updated:</strong> {{ productStock.lastUpdated | date:'yyyy-MM-dd HH:mm:ss' }}</li>
          </ul>
        </div>
        <div *ngIf="!productStock" class="text-muted mb-3">No product stock information found.</div>
      </div>
    </div>
  </div>
</div>
