// BungieReactApp3/src/pages/AdvancedUserManagement.jsx
import React, { useEffect, useState } from 'react';
import { Container, Row, Col, Card, Table, Button, Spinner, Alert, Modal, Form } from 'react-bootstrap';

const API_BASE = 'https://localhost:7226/api/Auth/users-with-extra-info-and-roles';
const ROLES_API = 'https://localhost:7226/api/Auth/roles';
const ADD_ROLE_API = 'https://localhost:7226/api/Auth/add-role-to-user';

export default function AdvancedUserManagement() {
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [expandedId, setExpandedId] = useState(null);
  const [roles, setRoles] = useState([]);
  const [showRoleModal, setShowRoleModal] = useState(false);
  const [selectedUser, setSelectedUser] = useState(null);
  const [selectedRole, setSelectedRole] = useState('');
  const [roleSubmitting, setRoleSubmitting] = useState(false);
  const [roleError, setRoleError] = useState('');
  const [roleSuccess, setRoleSuccess] = useState('');
  const token = localStorage.getItem('authToken');

  useEffect(() => {
    const fetchUsers = async () => {
      setLoading(true);
      setError('');
      try {
        const res = await fetch(API_BASE, {
          headers: {
            'accept': '*/*',
            'Authorization': `Bearer ${token}`,
          },
        });
        if (!res.ok) throw new Error('Failed to fetch users');
        const data = await res.json();
        setUsers(data);
      } catch (err) {
        setError('Error loading users');
      } finally {
        setLoading(false);
      }
    };

    const fetchRoles = async () => {
      try {
        const res = await fetch(ROLES_API, {
          headers: {
            'accept': '*/*',
            'Authorization': `Bearer ${token}`,
          },
        });
        if (!res.ok) throw new Error('Failed to fetch roles');
        const data = await res.json();
        setRoles(data);
      } catch (err) {
        // Roles error is not fatal for page
      }
    };

    fetchUsers();
    fetchRoles();
  }, [token]);

  const handleExpand = (id) => {
    setExpandedId(expandedId === id ? null : id);
  };

  const handleShowRoleModal = (user) => {
    setSelectedUser(user);
    setSelectedRole('');
    setRoleError('');
    setRoleSuccess('');
    setShowRoleModal(true);
  };

  const handleCloseRoleModal = () => {
    setShowRoleModal(false);
    setSelectedUser(null);
    setSelectedRole('');
    setRoleError('');
    setRoleSuccess('');
  };

  const handleRoleChange = (e) => {
    setSelectedRole(e.target.value);
  };

  const handleAddRole = async (e) => {
    e.preventDefault();
    if (!selectedRole) {
      setRoleError('Please select a role.');
      return;
    }
    setRoleSubmitting(true);
    setRoleError('');
    setRoleSuccess('');
    try {
      const res = await fetch(ADD_ROLE_API, {
        method: 'POST',
        headers: {
          'accept': '*/*',
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          email: selectedUser.email,
          role: selectedRole,
        }),
      });
      const data = await res.json();
      if (!res.ok || !data.success) {
        setRoleError(data.message || 'Failed to add role');
      } else {
        setRoleSuccess(data.message);
        // Optionally update user roles in UI
        setUsers((prev) =>
          prev.map((u) =>
            u.id === selectedUser.id
              ? { ...u, roles: [...(u.roles || []), selectedRole] }
              : u
          )
        );
      }
    } catch (err) {
      setRoleError('Error adding role');
    } finally {
      setRoleSubmitting(false);
    }
  };

  return (
    <Container className="mt-4">
      <Row className="justify-content-center">
        <Col md={10}>
          <Card className="shadow-sm mb-4">
            <Card.Body>
              <Card.Title as="h2" className="mb-3">User List</Card.Title>
              <Card.Text>
                List of users with key information. Click "Show Details" to view all user info.
              </Card.Text>
            </Card.Body>
          </Card>
          {error && <div className="alert alert-danger">{error}</div>}
          {loading ? (
            <div className="text-center"><Spinner animation="border" /></div>
          ) : (
            <Table striped bordered hover responsive>
              <thead>
                <tr>
                  <th>Email</th>
                  <th>User Name</th>
                  <th>Roles</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {users.map((user) => (
                  <React.Fragment key={user.id}>
                    <tr>
                      <td>{user.email}</td>
                      <td>{user.userName}</td>
                      <td>{user.roles && user.roles.join(', ')}</td>
                      <td>
                        <Button
                          variant="outline-info"
                          size="sm"
                          onClick={() => handleExpand(user.id)}
                          className="me-2"
                        >
                          {expandedId === user.id ? 'Hide Details' : 'Show Details'}
                        </Button>
                        <Button
                          variant="outline-success"
                          size="sm"
                          onClick={() => handleShowRoleModal(user)}
                        >
                          Add Role
                        </Button>
                      </td>
                    </tr>
                    {expandedId === user.id && (
                      <tr>
                        <td colSpan={4}>
                          <div style={{ background: '#f8f9fa', padding: '1rem', borderRadius: '6px' }}>
                            <strong>ID:</strong> {user.id}<br />
                            <strong>Email:</strong> {user.email}<br />
                            <strong>User Name:</strong> {user.userName}<br />
                            <strong>Roles:</strong> {user.roles && user.roles.join(', ')}<br />
                            <strong>Extra Info ID:</strong> {user.extraInfoId || 'N/A'}<br />
                            <strong>Full Name:</strong> {user.fullName || 'N/A'}<br />
                            <strong>Phone Number:</strong> {user.phoneNumber || 'N/A'}<br />
                            <strong>Role:</strong> {user.role || 'N/A'}<br />
                            <strong>Address:</strong> {user.address || 'N/A'}<br />
                            <strong>Registered Date:</strong> {user.registeredDate || 'N/A'}<br />
                            <strong>Is Active:</strong> {user.isActive === null ? 'N/A' : user.isActive ? 'Yes' : 'No'}<br />
                            <strong>Profile Image URL:</strong> {user.profileImageUrl || 'N/A'}
                          </div>
                        </td>
                      </tr>
                    )}
                  </React.Fragment>
                ))}
              </tbody>
            </Table>
          )}
        </Col>
      </Row>

      <Modal show={showRoleModal} onHide={handleCloseRoleModal} centered>
        <Modal.Header closeButton>
          <Modal.Title>Add Role to User</Modal.Title>
        </Modal.Header>
        <Form onSubmit={handleAddRole}>
          <Modal.Body>
            {roleError && <Alert variant="danger">{roleError}</Alert>}
            {roleSuccess && <Alert variant="success">{roleSuccess}</Alert>}
            <Form.Group className="mb-3">
              <Form.Label>User Email</Form.Label>
              <Form.Control type="text" value={selectedUser?.email || ''} disabled />
            </Form.Group>
            <Form.Group className="mb-3">
              <Form.Label>Select Role</Form.Label>
              <Form.Select value={selectedRole} onChange={handleRoleChange}>
                <option value="">-- Select Role --</option>
                {roles.map((role) => (
                  <option key={role.id} value={role.name}>{role.name}</option>
                ))}
              </Form.Select>
            </Form.Group>
          </Modal.Body>
          <Modal.Footer>
            <Button variant="secondary" onClick={handleCloseRoleModal}>
              Cancel
            </Button>
            <Button variant="success" type="submit" disabled={roleSubmitting}>
              {roleSubmitting ? 'Adding...' : 'Add Role'}
            </Button>
          </Modal.Footer>
        </Form>
      </Modal>
    </Container>
  );
}

// BungieCordBlogAngular3/src/app/features/advanced-user-management/advanced-user-management.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';

interface User {
  id: string;
  email: string;
  userName: string;
  roles: string[];
  extraInfoId: string | null;
  fullName: string | null;
  phoneNumber: string | null;
  role: string | null;
  address: string | null;
  registeredDate: string | null;
  isActive: boolean | null;
  profileImageUrl: string | null;
}

interface Role {
  id: string;
  name: string;
}

@Component({
  selector: 'app-advanced-user-management',
  templateUrl: './advanced-user-management.component.html',
  styleUrls: ['./advanced-user-management.component.css']
})
export class AdvancedUserManagementComponent implements OnInit {
  users: User[] = [];
  roles: Role[] = [];
  loading = false;
  error: string | null = null;
  detailsUserId: string | null = null;

  roleDropdownUserId: string | null = null;
  selectedRole: string = '';
  roleChangeLoading = false;
  roleChangeError: string | null = null;
  successMessage: string | null = null;

  private token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBCdW5naWVDb3JkQmxvZy5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOlsiUmVhZGVyIiwiV3JpdGVyIiwiQWRtaW4iXSwiZXhwIjoxNzU3ODAzODExLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MjI2IiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDIwMCJ9.0fC4VyH0MMCnvJ2ra8obnfKXeOAjiuLde5CKfwWkwvE';

  constructor(private http: HttpClient) {}

  ngOnInit(): void {
    this.fetchUsers();
    this.fetchRoles();
  }

  fetchUsers(): void {
    this.loading = true;
    this.error = null;
    const url = 'https://localhost:7226/api/Auth/users-with-extra-info-and-roles';
    const headers = new HttpHeaders({
      'accept': '*/*',
      'Authorization': `Bearer ${this.token}`
    });

    this.http.get<User[]>(url, { headers }).subscribe({
      next: (data) => {
        this.users = data;
        this.loading = false;
      },
      error: () => {
        this.error = 'Failed to load users.';
        this.loading = false;
      }
    });
  }

  fetchRoles(): void {
    const url = 'https://localhost:7226/api/Auth/roles';
    const headers = new HttpHeaders({
      'accept': '*/*',
      'Authorization': `Bearer ${this.token}`
    });

    this.http.get<Role[]>(url, { headers }).subscribe({
      next: (data) => {
        this.roles = data;
      },
      error: () => {
        this.roles = [];
      }
    });
  }

  toggleDetails(userId: string): void {
    this.detailsUserId = this.detailsUserId === userId ? null : userId;
  }

  openRoleDropdown(userId: string): void {
    this.roleDropdownUserId = userId;
    this.roleChangeError = null;
    this.successMessage = null;
    this.selectedRole = this.roles.length > 0 ? this.roles[0].name : '';
  }

  closeRoleDropdown(): void {
    this.roleDropdownUserId = null;
    this.roleChangeError = null;
    this.successMessage = null;
  }

  changeUserRole(email: string): void {
    if (!this.selectedRole) {
      this.roleChangeError = 'Please select a role.';
      return;
    }
    this.roleChangeLoading = true;
    this.roleChangeError = null;
    this.successMessage = null;

    const url = 'https://localhost:7226/api/Auth/add-role-to-user';
    const headers = new HttpHeaders({
      'accept': '*/*',
      'Authorization': `Bearer ${this.token}`,
      'Content-Type': 'application/json'
    });

    const body = {
      email: email,
      role: this.selectedRole
    };

    this.http.post<any>(url, body, { headers }).subscribe({
      next: (response) => {
        this.roleChangeLoading = false;
        if (response && response.success) {
          this.successMessage = response.message;
          this.closeRoleDropdown();
          this.fetchUsers(); // Refresh user list to show updated roles
        } else {
          this.roleChangeError = response.message || 'Failed to change role.';
        }
      },
      error: () => {
        this.roleChangeLoading = false;
        this.roleChangeError = 'Failed to change role.';
      }
    });
  }
}
<div class="container-fluid my-5">
  <div class="row justify-content-center">
    <div class="col-12 col-md-10">
      <h2 class="text-center mb-4">Advanced User Management</h2>
      <div *ngIf="loading" class="text-center my-3">
        <span class="spinner-border"></span> Loading users...
      </div>
      <div *ngIf="error" class="alert alert-danger text-center">{{ error }}</div>
      <div *ngIf="successMessage" class="alert alert-success text-center">{{ successMessage }}</div>
      <div class="table-responsive">
        <table *ngIf="users && !loading" class="table table-sm table-bordered table-striped align-middle">
          <thead>
            <tr>
              <th>Email</th>
              <th>User Name</th>
              <th>Roles</th>
              <th>Active</th>
            </tr>
          </thead>
          <tbody>
            <ng-container *ngFor="let user of users">
              <tr>
                <td>{{ user.email }}</td>
                <td>{{ user.userName }}</td>
                <td>
                  <span *ngFor="let role of user.roles; let last = last">
                    {{ role }}<span *ngIf="!last">, </span>
                  </span>
                </td>
                <!-- <td>{{ user.isActive === true ? 'Yes' : user.isActive === false ? 'No' : '-' }}</td> -->
                <td>
                  <button class="btn btn-info btn-sm me-1" (click)="toggleDetails(user.id)">
                    {{ detailsUserId === user.id ? 'Hide Details' : 'Show Details' }}
                  </button>
                  <button class="btn btn-warning btn-sm" (click)="openRoleDropdown(user.id)">
                    Change Role
                  </button>
                  <div *ngIf="roleDropdownUserId === user.id" class="mt-2">
                    <div class="input-group input-group-sm">
                      <select class="form-select" [(ngModel)]="selectedRole">
                        <option *ngFor="let role of roles" [value]="role.name">{{ role.name }}</option>
                      </select>
                      <button class="btn btn-success" (click)="changeUserRole(user.email)">Confirm</button>
                      <button class="btn btn-secondary" (click)="closeRoleDropdown()">Cancel</button>
                    </div>
                    <div *ngIf="roleChangeLoading" class="mt-2 text-info">
                      <span class="spinner-border spinner-border-sm"></span> Changing role...
                    </div>
                    <div *ngIf="roleChangeError" class="mt-2 text-danger">
                      {{ roleChangeError }}
                    </div>
                  </div>
                </td>
              </tr>
              <tr *ngIf="detailsUserId === user.id">
                <td colspan="5">
                  <div class="card mt-2 mb-2">
                    <div class="card-body">
                      <h5 class="card-title">User Details</h5>
                      <ul class="list-unstyled mb-2">
                        <li><strong>Email:</strong> {{ user.email }}</li>
                        <li><strong>User Name:</strong> {{ user.userName }}</li>
                        <li><strong>Roles:</strong> {{ user.roles.join(', ') }}</li>
                        <li><strong>Full Name:</strong> {{ user.fullName || '-' }}</li>
                        <li><strong>Phone Number:</strong> {{ user.phoneNumber || '-' }}</li>
                        <li><strong>Address:</strong> {{ user.address || '-' }}</li>
                        <li><strong>Registered Date:</strong> {{ user.registeredDate ? (user.registeredDate | date:'yyyy-MM-dd') : '-' }}</li>
                        <li><strong>Active:</strong> {{ user.isActive === true ? 'Yes' : user.isActive === false ? 'No' : '-' }}</li>
                        <li>
                          <strong>Profile Image:</strong>
                          <img *ngIf="user.profileImageUrl" [src]="user.profileImageUrl" alt="Profile" style="width:60px; height:60px; object-fit:cover;">
                          <span *ngIf="!user.profileImageUrl">-</span>
                        </li>
                      </ul>
                    </div>
                  </div>
                </td>
              </tr>
            </ng-container>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
