// BungieCordBlogAngular2/src/app/features/user-profile/user-profile.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { CookieService } from 'ngx-cookie-service';

interface Order {
  id: string;
  userId: string;
  email: string;
  paymentId: string;
  status: number;
  createdDate: string;
  updatedDate: string;
  statusString: string;
}

interface ExtraUserInfo {
  id: string;
  email: string;
  fullName: string;
  phoneNumber: string;
  role: string;
  address: string;
  registeredDate: string;
  isActive: boolean;
  profileImageUrl: string;
}

@Component({
  selector: 'app-user-profile',
  templateUrl: './user-profile.component.html'
})
export class UserProfileComponent implements OnInit {
  profile: any = null;
  token: string | null = null;
  errorMessage: string = '';
  copied = false;
  useremail: string | null = null;

  profileVisible = true;

  orders: Order[] = [];
  ordersLoading = false;
  ordersError = '';
  ordersVisible = false;

  extraUserInfo: ExtraUserInfo | null = null;
  extraUserInfoLoading = false;
  extraUserInfoError = '';
  extraUserInfoVisible = false;

  extraUserInfoUpdating = false;
  extraUserInfoUpdateError = '';
  extraUserInfoUpdateSuccess = false;

  constructor(private http: HttpClient, private cookieService: CookieService) {}

  ngOnInit() {
    let token = this.cookieService.get('Authorization');
    if (token) {
      this.token = token;
      const headers = new HttpHeaders().set('Authorization', token);
      this.http.get('https://localhost:7226/api/Auth/token-details', { headers })
      .subscribe({
        next: (data: any) => {
          this.profile = data;
          this.useremail = this.profile.email;
        },
        error: () => this.errorMessage = 'Failed to load profile.'
      });
    } else {
      this.errorMessage = 'No token found. Please login.';
    }
  }

  toggleProfile() {
    this.profileVisible = !this.profileVisible;
  }

  toggleOrders() {
    if (this.ordersVisible) {
      this.ordersVisible = false;
    } else {
      this.ordersVisible = true;
      this.ordersLoading = true;
      this.ordersError = '';
      this.http.get<Order[]>(`https://localhost:7226/api/Payment/orders/by-email?email=${this.useremail}`)
        .subscribe({
          next: data => {
            this.orders = data;
            this.ordersLoading = false;
          },
          error: () => {
            this.ordersError = 'Could not load orders.';
            this.ordersLoading = false;
          }
        });
    }
  }

  copyToken() {
    if (this.token) {
      navigator.clipboard.writeText(this.token).then(() => {
        this.copied = true;
        setTimeout(() => this.copied = false, 1500);
      });
    }
  }

  toggleExtraUserInfo() {
    if (this.extraUserInfoVisible) {
      this.extraUserInfoVisible = false;
    } else {
      this.extraUserInfoVisible = true;
      if (!this.extraUserInfo) {
        this.loadExtraUserInfo();
      }
    }
  }

  loadExtraUserInfo() {
    if (!this.useremail) return;
    this.extraUserInfoLoading = true;
    this.extraUserInfoError = '';
    this.extraUserInfo = null;
    this.extraUserInfoUpdateError = '';
    this.extraUserInfoUpdateSuccess = false;
    const encodedEmail = encodeURIComponent(this.useremail);
    this.http.get<ExtraUserInfo>(`https://localhost:7226/api/UserExtraInfo/by-email/${encodedEmail}`)
      .subscribe({
        next: (data) => {
          this.extraUserInfo = data;
          this.extraUserInfoLoading = false;
        },
        error: () => {
          this.extraUserInfoError = 'Failed to load extra user info.';
          this.extraUserInfoLoading = false;
        }
      });
  }

  updateExtraUserInfo() {
    if (!this.extraUserInfo || !this.extraUserInfo.id) return;
    this.extraUserInfoUpdating = true;
    this.extraUserInfoUpdateError = '';
    this.extraUserInfoUpdateSuccess = false;
    const updatePayload = {
      fullName: this.extraUserInfo.fullName,
      phoneNumber: this.extraUserInfo.phoneNumber,
      role: this.extraUserInfo.role,
      address: this.extraUserInfo.address,
      isActive: this.extraUserInfo.isActive,
      profileImageUrl: this.extraUserInfo.profileImageUrl
    };
    this.http.put<ExtraUserInfo>(
      `https://localhost:7226/api/UserExtraInfo/${this.extraUserInfo.id}`,
      updatePayload
    ).subscribe({
      next: (data) => {
        this.extraUserInfo = data;
        this.extraUserInfoUpdating = false;
        this.extraUserInfoUpdateSuccess = true;
        setTimeout(() => this.extraUserInfoUpdateSuccess = false, 2000);
      },
      error: () => {
        this.extraUserInfoUpdateError = 'Failed to update extra user info.';
        this.extraUserInfoUpdating = false;
      }
    });
  }
}
<div class="container mt-5">
  <div class="col-12 col-md-6 col-lg-4 mx-auto">
    <button class="btn btn-secondary mb-3" (click)="toggleProfile()">
      {{ profileVisible ? 'Hide User Profile' : 'Show User Profile' }}
    </button>
    <div *ngIf="profileVisible">
      <h1>User Profile</h1>
      <div *ngIf="errorMessage" class="alert alert-danger">{{ errorMessage }}</div>
      <div *ngIf="profile">
        <p><strong>Email:</strong> {{ profile.email }}</p>
        <p><strong>Roles:</strong> {{ profile.roles.join(', ') }}</p>
        <p><strong>Issuer:</strong> {{ profile.issuer }}</p>
        <p><strong>Audience:</strong> {{ profile.audience.join(', ') }}</p>
        <p><strong>Expiry:</strong> {{ profile.expiry | date:'medium' }}</p>
        <div>
          <strong>Token:</strong>
          <pre class="bg-light p-2 mb-2" style="white-space: pre-wrap; word-break: break-all;">{{ token }}</pre>
          <button class="btn btn-sm btn-outline-secondary" (click)="copyToken()">Copy</button>
          <span *ngIf="copied" class="ms-2 text-success">Copied!</span>
        </div>
        <!-- Show/Hide Orders Button -->
        <button class="btn btn-primary mt-3" (click)="toggleOrders()">
          {{ ordersVisible ? 'Hide Orders' : 'Show Orders' }}
        </button>
        <!-- Toggle Extra User Info Button -->
        <button class="btn btn-info mt-3 ms-2" (click)="toggleExtraUserInfo()">
          {{ extraUserInfoVisible ? 'Hide Extra User Info' : 'Show Extra User Info' }}
        </button>
      </div>
    </div>
  </div>

  <!-- Orders Section -->
  <div class="col-12 col-md-8 col-lg-6 mx-auto mt-5" *ngIf="ordersVisible">
    <h2>Order History</h2>
    <div *ngIf="ordersLoading" class="my-3">
      <span class="spinner-border spinner-border-sm"></span> Loading orders...
    </div>
    <div *ngIf="ordersError" class="alert alert-danger">{{ ordersError }}</div>
    <table *ngIf="orders.length > 0" class="table table-bordered table-striped mt-3">
      <thead>
        <tr>
          <th>Order ID</th>
          <th>Status</th>
          <th>Created</th>
          <th>Updated</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let order of orders">
          <td>{{ order.id }}</td>
          <td>{{ order.statusString }}</td>
          <td>{{ order.createdDate | date:'yyyy-MM-dd HH:mm:ss' }}</td>
          <td>{{ order.updatedDate | date:'yyyy-MM-dd HH:mm:ss' }}</td>
        </tr>
      </tbody>
    </table>
    <div *ngIf="!ordersLoading && orders.length === 0" class="alert alert-info mt-3">
      No orders found.
    </div>
  </div>

  <!-- Extra User Info Section -->
  <div class="col-12 col-md-8 col-lg-6 mx-auto mt-5" *ngIf="extraUserInfoVisible">
    <div *ngIf="extraUserInfoLoading">
      <span class="spinner-border spinner-border-sm"></span> Loading extra user info...
    </div>
    <div *ngIf="extraUserInfoError">
      <div class="alert alert-danger">{{ extraUserInfoError }}</div>
    </div>
    <div *ngIf="extraUserInfo">
      <h2>Extra User Info</h2>
      <form (ngSubmit)="updateExtraUserInfo()" #extraUserInfoForm="ngForm">
        <table class="table table-bordered table-striped">
          <tbody>
            <tr>
              <th>Email</th>
              <td>{{ extraUserInfo.email }}</td>
            </tr>
            <tr>
              <th>Full Name</th>
              <td>
                <input class="form-control" [(ngModel)]="extraUserInfo.fullName" name="fullName" required>
              </td>
            </tr>
            <tr>
              <th>Phone Number</th>
              <td>
                <input class="form-control" [(ngModel)]="extraUserInfo.phoneNumber" name="phoneNumber">
              </td>
            </tr>
            <tr>
              <th>Role</th>
              <td>
                <input class="form-control" [(ngModel)]="extraUserInfo.role" name="role">
              </td>
            </tr>
            <tr>
              <th>Address</th>
              <td>
                <input class="form-control" [(ngModel)]="extraUserInfo.address" name="address">
              </td>
            </tr>
            <tr>
              <th>Registered Date</th>
              <td>{{ extraUserInfo.registeredDate | date:'medium' }}</td>
            </tr>
            <tr>
              <th>Active</th>
              <td>
                <input type="checkbox" class="form-check-input" [(ngModel)]="extraUserInfo.isActive" name="isActive">
                <label class="form-check-label ms-2">{{ extraUserInfo.isActive ? 'Yes' : 'No' }}</label>
              </td>
            </tr>
            <!-- <tr>
              <th>Profile Image</th>
              <td>
                <input class="form-control mb-2" [(ngModel)]="extraUserInfo.profileImageUrl" name="profileImageUrl">
                <img *ngIf="extraUserInfo.profileImageUrl" [src]="extraUserInfo.profileImageUrl" alt="Profile" style="width:60px;height:60px;">
              </td>
            </tr> -->
          </tbody>
        </table>
        <button type="submit" class="btn btn-success me-2" [disabled]="extraUserInfoUpdating">Update</button>
        <span *ngIf="extraUserInfoUpdateError" class="text-danger ms-2">{{ extraUserInfoUpdateError }}</span>
        <span *ngIf="extraUserInfoUpdateSuccess" class="text-success ms-2">Updated!</span>
      </form>
    </div>
  </div>
</div>

// BungieReactApp3/src/pages/UserProfile.jsx
import React, { useState, useEffect } from 'react';
import { Button, Modal, Form, Spinner, Alert, Image } from 'react-bootstrap';

export default function UserProfile() {
  const email = localStorage.getItem('authEmail');
  const token = localStorage.getItem('authToken');
  const roles = JSON.parse(localStorage.getItem('authRoles') || '[]');
  const [copied, setCopied] = useState(false);
  const [tokenDetails, setTokenDetails] = useState(null);
  const [loading, setLoading] = useState(false);
  const [fetchError, setFetchError] = useState(null);

  // Orders state
  const [orders, setOrders] = useState([]);
  const [ordersLoading, setOrdersLoading] = useState(false);
  const [ordersError, setOrdersError] = useState('');
  const [showOrders, setShowOrders] = useState(false);

  // Extra User Info state
  const [showExtraInfo, setShowExtraInfo] = useState(false);
  const [extraInfo, setExtraInfo] = useState(null);
  const [extraInfoLoading, setExtraInfoLoading] = useState(false);
  const [extraInfoError, setExtraInfoError] = useState('');
  const [showEditModal, setShowEditModal] = useState(false);
  const [editForm, setEditForm] = useState({
    fullName: '',
    phoneNumber: '',
    role: '',
    address: '',
    isActive: true,
    profileImageUrl: '',
  });
  const [editSubmitting, setEditSubmitting] = useState(false);
  const [editError, setEditError] = useState('');
  const [editNotification, setEditNotification] = useState('');

  const handleCopy = async () => {
    if (token) {
      try {
        await navigator.clipboard.writeText(token);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      } catch (err) {
        // Optionally handle error
      }
    }
  };

  useEffect(() => {
    if (!token) return;
    setLoading(true);
    fetch('https://localhost:7226/api/Auth/token-details', {
      method: 'GET',
      headers: {
        'accept': '*/*',
        'Authorization': `Bearer ${token}`
      }
    })
      .then(async (res) => {
        if (!res.ok) throw new Error('Failed to fetch token details');
        return await res.json();
      })
      .then(data => {
        setTokenDetails(data);
        setFetchError(null);
      })
      .catch(err => {
        setFetchError('Could not fetch token details.');
      })
      .finally(() => setLoading(false));
  }, [token]);

  // Fetch orders by email
  const fetchOrders = async () => {
    if (!email) return;
    setOrdersLoading(true);
    setOrdersError('');
    try {
      const res = await fetch(`https://localhost:7226/api/Payment/orders/by-email?email=${encodeURIComponent(email)}`, {
        headers: { 'accept': '*/*' }
      });
      if (!res.ok) throw new Error('Failed to fetch orders');
      const data = await res.json();
      setOrders(data);
    } catch (err) {
      setOrdersError('Could not fetch orders.');
    } finally {
      setOrdersLoading(false);
    }
  };

  // Toggle orders display
  const handleToggleOrders = () => {
    if (!showOrders) {
      fetchOrders();
    }
    setShowOrders(prev => !prev);
  };

  // Fetch extra user info by email
  const fetchExtraInfo = async () => {
    if (!email) return;
    setExtraInfoLoading(true);
    setExtraInfoError('');
    try {
      const res = await fetch(`https://localhost:7226/api/UserExtraInfo/by-email/${encodeURIComponent(email)}`, {
        headers: { 'accept': '*/*' }
      });
      if (!res.ok) throw new Error('Failed to fetch extra info');
      const data = await res.json();
      setExtraInfo(data);
    } catch (err) {
      setExtraInfoError('Could not fetch extra user info.');
      setExtraInfo(null);
    } finally {
      setExtraInfoLoading(false);
    }
  };

  // Toggle extra info display
  const handleToggleExtraInfo = () => {
    if (!showExtraInfo) {
      fetchExtraInfo();
    }
    setShowExtraInfo(prev => !prev);
  };

  // Open edit modal
  const handleOpenEditModal = () => {
    if (!extraInfo) return;
    setEditForm({
      fullName: extraInfo.fullName || '',
      phoneNumber: extraInfo.phoneNumber || '',
      role: extraInfo.role || '',
      address: extraInfo.address || '',
      isActive: !!extraInfo.isActive,
      profileImageUrl: extraInfo.profileImageUrl || '',
    });
    setEditError('');
    setShowEditModal(true);
  };

  // Handle edit form change
  const handleEditFormChange = (e) => {
    const { name, value, type, checked } = e.target;
    setEditForm(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value,
    }));
  };

  // Submit edit form
  const handleEditSubmit = async (e) => {
    e.preventDefault();
    if (!extraInfo?.id) return;
    setEditSubmitting(true);
    setEditError('');
    try {
      const res = await fetch(`https://localhost:7226/api/UserExtraInfo/${extraInfo.id}`, {
        method: 'PUT',
        headers: { 'accept': '*/*', 'Content-Type': 'application/json' },
        body: JSON.stringify(editForm),
      });
      if (!res.ok) throw new Error('Failed to update extra info');
      const data = await res.json();
      setExtraInfo(data);
      setShowEditModal(false);
      setEditNotification('Extra user info updated successfully!');
      setTimeout(() => setEditNotification(''), 3000);
    } catch (err) {
      setEditError('Could not update extra user info.');
    } finally {
      setEditSubmitting(false);
    }
  };

  if (!token) {
    return (
      <div className="container mt-5">
        <h2>User Profile</h2>
        <div className="alert alert-warning">You are not logged in.</div>
      </div>
    );
  }

  return (
    <div className="container mt-5 position-relative">
      <h2>User Profile</h2>
      <div className="mb-3">
        <strong>Email:</strong> {email}
      </div>
      <div className="mb-3">
        <strong>Token:</strong>
        <div
          style={{
            wordBreak: 'break-all',
            fontSize: '0.9em',
            background: '#f8f9fa',
            padding: '8px',
            borderRadius: '4px',
            display: 'flex',
            alignItems: 'center',
            gap: '8px'
          }}
        >
          <span style={{ flex: 1 }}>{token}</span>
          <button
            className="btn btn-outline-secondary btn-sm"
            onClick={handleCopy}
            style={{ whiteSpace: 'nowrap' }}
          >
            Copy
          </button>
        </div>
      </div>
      <div className="mb-3">
        <strong>Roles:</strong>
        <ul>
          {roles.map((role, idx) => (
            <li key={idx}>{role}</li>
          ))}
        </ul>
      </div>
      <hr />
      <h4>Token Details</h4>
      {loading && <div className="text-muted">Loading token details...</div>}
      {fetchError && <div className="alert alert-danger">{fetchError}</div>}
      {tokenDetails && (
        <div className="mb-3">
          <div><strong>Email:</strong> {tokenDetails.email}</div>
          <div><strong>Issuer:</strong> {tokenDetails.issuer}</div>
          <div><strong>Audience:</strong> {Array.isArray(tokenDetails.audience) ? tokenDetails.audience.join(', ') : tokenDetails.audience}</div>
          <div><strong>Expiry:</strong> {tokenDetails.expiry}</div>
          <div><strong>Roles:</strong>
            <ul>
              {tokenDetails.roles.map((role, idx) => (
                <li key={idx}>{role}</li>
              ))}
            </ul>
          </div>
          <div>
            <strong>Claims:</strong>
            <ul>
              {tokenDetails.claims &&
                Object.entries(tokenDetails.claims).map(([key, value]) => (
                  <li key={key}>
                    <span style={{ fontWeight: 500 }}>{key}:</span> {Array.isArray(value) ? value.join(', ') : value}
                  </li>
                ))}
            </ul>
          </div>
        </div>
      )}

      <div className="mb-4">
        <button
          className="btn btn-info"
          onClick={handleToggleOrders}
          disabled={ordersLoading}
        >
          {showOrders ? 'Hide Orders' : 'Show Orders'}
        </button>
      </div>

      {/* Extra User Info Button */}
      <div className="mb-4">
        <Button
          variant="outline-primary"
          onClick={handleToggleExtraInfo}
          disabled={extraInfoLoading}
        >
          {showExtraInfo ? 'Hide Extra User Info' : 'Show Extra User Info'}
        </Button>
      </div>

      {/* Extra User Info Section */}
      {showExtraInfo && (
        <div className="mb-4">
          <h4>Extra User Info</h4>
          {extraInfoLoading && <div className="text-muted">Loading extra user info...</div>}
          {extraInfoError && <div className="alert alert-danger">{extraInfoError}</div>}
          {extraInfo && (
            <div className="card p-3 mb-3">
              <div className="row">
                <div className="col-md-2">
                  {extraInfo.profileImageUrl ? (
                    <Image src={extraInfo.profileImageUrl} rounded width={80} height={80} alt="Profile" />
                  ) : (
                    <div className="bg-light text-muted text-center" style={{ width: 80, height: 80, lineHeight: '80px' }}>
                      No Image
                    </div>
                  )}
                </div>
                <div className="col-md-10">
                  <div><strong>Email:</strong> {extraInfo.email}</div>
                  <div><strong>Full Name:</strong> {extraInfo.fullName}</div>
                  <div><strong>Phone Number:</strong> {extraInfo.phoneNumber}</div>
                  <div><strong>Role:</strong> {extraInfo.role}</div>
                  <div><strong>Address:</strong> {extraInfo.address}</div>
                  <div><strong>Registered Date:</strong> {extraInfo.registeredDate?.replace('T', ' ').slice(0, 19)}</div>
                  <div><strong>Active:</strong> {extraInfo.isActive ? 'Yes' : 'No'}</div>
                </div>
              </div>
              <div className="mt-3">
                <Button variant="outline-secondary" size="sm" onClick={handleOpenEditModal}>
                  Edit Extra Info
                </Button>
              </div>
            </div>
          )}
        </div>
      )}

      {/* Edit Modal */}
      <Modal show={showEditModal} onHide={() => setShowEditModal(false)}>
        <Form onSubmit={handleEditSubmit}>
          <Modal.Header closeButton>
            <Modal.Title>Edit Extra User Info</Modal.Title>
          </Modal.Header>
          <Modal.Body>
            <Form.Group className="mb-3">
              <Form.Label>Full Name</Form.Label>
              <Form.Control
                name="fullName"
                value={editForm.fullName}
                onChange={handleEditFormChange}
                required
              />
            </Form.Group>
            <Form.Group className="mb-3">
              <Form.Label>Phone Number</Form.Label>
              <Form.Control
                name="phoneNumber"
                value={editForm.phoneNumber}
                onChange={handleEditFormChange}
                required
              />
            </Form.Group>
            <Form.Group className="mb-3">
              <Form.Label>Role</Form.Label>
              <Form.Control
                name="role"
                value={editForm.role}
                onChange={handleEditFormChange}
                required
              />
            </Form.Group>
            <Form.Group className="mb-3">
              <Form.Label>Address</Form.Label>
              <Form.Control
                name="address"
                value={editForm.address}
                onChange={handleEditFormChange}
                required
              />
            </Form.Group>
            <Form.Group className="mb-3">
              <Form.Check
                name="isActive"
                label="Active"
                checked={editForm.isActive}
                onChange={handleEditFormChange}
                type="checkbox"
              />
            </Form.Group>
            <Form.Group className="mb-3">
              <Form.Label>Profile Image URL</Form.Label>
              <Form.Control
                name="profileImageUrl"
                value={editForm.profileImageUrl}
                onChange={handleEditFormChange}
                placeholder="Paste image URL here"
              />
            </Form.Group>
            {editError && <Alert variant="danger">{editError}</Alert>}
          </Modal.Body>
          <Modal.Footer>
            <Button variant="secondary" onClick={() => setShowEditModal(false)}>
              Cancel
            </Button>
            <Button variant="primary" type="submit" disabled={editSubmitting}>
              {editSubmitting ? 'Saving...' : 'Save'}
            </Button>
          </Modal.Footer>
        </Form>
      </Modal>

      {/* Edit Notification */}
      {editNotification && (
        <div
          style={{
            position: 'fixed',
            top: 20,
            right: 20,
            zIndex: 1050,
            minWidth: 300,
            maxWidth: '80vw'
          }}
        >
          <Alert
            variant="success"
            onClose={() => setEditNotification('')}
            dismissible
          >
            {editNotification}
          </Alert>
        </div>
      )}

      {showOrders && (
        <div className="mb-4">
          <h4>Your Orders</h4>
          {ordersLoading && <div className="text-muted">Loading orders...</div>}
          {ordersError && <div className="alert alert-danger">{ordersError}</div>}
          {!ordersLoading && !ordersError && orders.length === 0 && (
            <div className="alert alert-warning">No orders found.</div>
          )}
          {!ordersLoading && !ordersError && orders.length > 0 && (
            <div className="table-responsive">
              <table className="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Order ID</th>
                    <th>Payment ID</th>
                    <th>Status</th>
                    <th>Status String</th>
                    <th>Created Date</th>
                    <th>Updated Date</th>
                  </tr>
                </thead>
                <tbody>
                  {orders.map(order => (
                    <tr key={order.id}>
                      <td>{order.id}</td>
                      <td>{order.paymentId}</td>
                      <td>{order.status}</td>
                      <td>{order.statusString}</td>
                      <td>{order.createdDate?.replace('T', ' ').slice(0, 19)}</td>
                      <td>{order.updatedDate?.replace('T', ' ').slice(0, 19)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}

      {copied && (
        <div
          style={{
            position: 'fixed',
            top: '20px',
            left: '50%',
            transform: 'translateX(-50%)',
            zIndex: 1050,
            minWidth: '200px',
            maxWidth: '90vw'
          }}
        >
          <div className="alert alert-success py-2 px-3 mb-0 text-center shadow" style={{ fontSize: '1em' }}>
            Token copied!
          </div>
        </div>
      )}
    </div>
  );
}
